version: '3.8'

services:

  convnn:
    build:
      context: ./convnn
      dockerfile: Dockerfile
    ports:
      - 5001:5000

  nginx:
    build:
      context: ./nginx
      dockerfile: Dockerfile
    restart: always
    ports:
      - 80:80
    depends_on:
      - convnn      

